apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: {{ .Values.frontEndPort }}
    protocol: TCP
  selector:
    app: guestbook
    tier: frontend
