apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: "{{ .Values.frontEndDomain }}"
      http:
        paths:
          - backend:
              service:
                name: cluster-ip
                port:
                  number: {{ .Values.frontEndPort }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "{{ .Values.frontEndDomain }}"
      secretName: wildcard